//Program: CS201PGM9Grading
//Name: Johnny Diep
//Date: 02/25/2024
//Purpose: Read student ID and answers and then calculate their corresponding grades
//Writes the ID, answers, grades, and percentages to the report file and writes an erroneous IDs to the error file

#include "functions.h"
#include <iostream>
using namespace std;

int main()
{
    //Psuedcode generated by CHATGPT and then further modified
    /*
     * Open error file
Open report file

If errFile cannot be opened Then
    Display "The error file cannot be opened"
    Return 1
End If

If reportFile cannot be opened Then
    Display "The report file cannot be opened"
    Return 1
End If

Create an empty vector of pointers to studentInfo named studentData

Call processStudentData(errFile, studentData)

Call printReport(reportFile, studentData)

Close errFile
Close reportFile

     */

    ofstream errFile, reportFile;
    //Opens Files
    errFile.open(R"(C:\Users\Johnny\CLionProjects\cs201-program9-grading-Powerstar0\CS201PGM9-GradingTemplate\error.txt)");
    reportFile.open("C:\\Users\\Johnny\\CLionProjects\\cs201-program9-grading-Powerstar0\\CS201PGM9-GradingTemplate\\report.txt");
    //Checks if they are open
    if (!errFile.is_open()) {
        cout << "The error file cannot be opened" << endl;
        return 1;
    }
    if (!reportFile.is_open()) {
        cout << "The report file cannot be opened" << endl;
        return 1;
    }
    //Create an empty vector of pointers
    vector<studentInfo*> studentData;
    //Calls functions to process the data and write it
    processStudentData(errFile, studentData);
    printReport(reportFile, studentData);
    //Close files
    errFile.close();
    reportFile.close();
}
 